### ISSUE TITLE
Containers in Multiplayer spawn at 0, 0, 0 for other players

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1047]
Spawn a container in MP, you see it there fine. But the other players see it at 0, 0, 0 and the rorbot also stays there in crucifixion :P

http://i.imgur.com/OnMInXr.png

Also this sometimes happens with normal vehicles too

https://files.gitter.im/tritonas00/RtT1/2016-06-06-002722_1366x768_scrot.png

**Comment by ulteq** [comment]
This could be solved by including the initial truck position and rotation into the stream setup message:
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/network/protocol/rornet.h#L163-L185

**Comment by only-a-ptr** [comment]
working on it: http://forum.rigsofrods.org/thread-458-post-4466.html#pid4466

**Comment by graysonk95** [comment]
The issue with weird things happening at 0,0,0 has been around for as long as I can remember (and I've been using multiplayer since it was "fixed" for v37). This exact issue was especially bad about two or 3 years ago. Whenever I was playing with my private MP group vehicles were spawning at 0,0,0 and we couldn't see each other and all had to keep reloading RoR until we all could see each other and we had to deal with the giant crucified RoRbot.
I'm glad to see this is being worked on.

I made this 0,0,0 issue not too long ago and it has since been closed: https://github.com/RigsOfRods/rigs-of-rods/issues/27

**Comment by ulteq** [comment]
#27 is unrelated to this new issue.

**Comment by tritonas00** [comment]
Still valid

**Comment by tritonas00** [comment]
the clients had somewhat different *.zip.

i downloaded the same as the other player, and the issue resolved.
