### ISSUE TITLE
Deactivation of full screen option isn't persisted across restarts

### ISSUE THREAD

**Issue by krichter722** [RigsOfRods/rigs-of-rods#1096]
Deactivation of full screen option isn't persisted across restarts.

experienced with 0.4.6.0-dev-64ad6f6 on Ubuntu 16.04

**Comment by disloyalpick** [comment]
Do you mean, that you disable fullscreen, and it will re-enable after a re-boot?  

I can't say I've ever experienced something like that. But make sure you're changing the setting from the Actual RoRConfig.exe file instead of the GUI settings menu.

**Comment by krichter722** [comment]
> I can't say I've ever experienced something like that. But make sure you're changing the setting from the Actual RoRConfig.exe file instead of the GUI settings menu.

Not sure how to change something in a compiled binary. Should have mentioned that I'm on Ubuntu 16.04, but there I can't change compiled binaries neither. Shouldn't the GUI just work?

**Comment by only-a-ptr** [comment]
how exactly did you de-activate the fullscreen? 
* Did you edit ror.cfg,?
* Did you use rorconfig?
* did you run ror with "-setup" commandline switch and adjusted the settings in the OGRE config box?

It's possible that the problem is caused by RoRConfig (the configurator). It always loads ror.cfg and overwrites it. It might drop some values.
