### ISSUE TITLE
Error handling: more informative crash reports.

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#1115]
Currently, RoR shows a very raw technical error dialog on crash:
![ogreexception---14732089116571435601111](https://cloud.githubusercontent.com/assets/491088/18346797/9014064e-75c2-11e6-8cc5-408b8aacd3c6.jpg)

Instead, the dialog should say :
```
FATAL ERROR

An internal error occured in Rigs of Rods
Technical details below:
Ogre exception blah blah
```

**Comment by AnotherFoxGuy** [comment]
The code for the dialog box can be found here:
http://developer.rigsofrods.org/doxygen/struct_error_utils.html#a03b1f233c5e57c4a7418b1d1ca072343

**Comment by AnotherFoxGuy** [comment]
![ror_2016-09-15_09-29-36](https://cloud.githubusercontent.com/assets/9480940/18542062/12b45ec6-7b29-11e6-8d80-4e8d35ed4a69.png)

Any comments?

**Comment by ulteq** [comment]
Do those wiki pages already exist?

**Comment by only-a-ptr** [comment]
Let's remove those URLs (+ open in browser? buttons) altogether. Those pages don't exist and we won't create new ones. If the problem is easy to solve, we should tell the player directly in the error message. If not, bummer.

**Comment by Michael10055** [comment]
Most of the wiki pages weren't that helpful either, for example: https://xror.avrintech.net/rorwikibackup/index.php/Error_7

**Comment by DarthCainRor** [comment]
As @Michael10055 said, the error message wiki pages where rarely actually helpful, except for error 5 potentially. Which isn't even an issue really anymore with the new Parser, that doesn't crash the game upon loading something with an improperly defined placement line.  Most of them were half written, with no real clue on what the actual culprit was.
