### ISSUE TITLE
RoR 0.4.7 attachments falling off

### ISSUE THREAD

**Issue by negativeice** [RigsOfRods/rigs-of-rods#1264]
anything that uses hooks/lockgroups detaches when you leave the vehicle and enter a different one, when you go back into the vehicle the attachment fell off from, it snaps back into palce and sometimes breaks everything.

video
https://www.youtube.com/watch?v=biW-_BCxq-g

**Comment by Michael10055** [comment]
A workaround is to click `Activated vehicles never sleep` from the top menu.

**Comment by negativeice** [comment]
From my testing just activating all vehicles does the trick

**Comment by only-a-ptr** [comment]
I'm trying to reproduce it with LIEBHERR I556 Loader+Bucket and I'm getting weird mixed results.

Once I lifted the bucket about half the way, left the vehicle and walked away on foot. The bucket just dropped down by itself. I walked back and entered the vehicle -> it exploded.

I tried repeating the scenario, but this time, the bucket didn't fall off and the vehicle wouldn't wake up, it would even let me drive thru it with a Bobcat.

Other things I've seen:
* Liebher drops the bucket once AgoraS bus drives close
* Liebher never lets go of the bucket, even when AgoraS bumps it, goes away, returns...
* Liebher drops the bucket and when AgoraS draws close, it leaps into stratosphere. Yes it happened.

**Comment by only-a-ptr** [comment]
I'm fixing it here: https://github.com/only-a-ptr/rigs-of-rods/tree/inter-beam-research

The problem is RoR's concept of "beam connected to another actor (=truck)". Such beams are still owned by one of the actors, they just carry info about the connection. The code was chaotic and buggy from the beginning. Ulteq tried very hard to give it some structure, he practically isolated those interconnecting beams from the common ones, but obviously, it's still not enough.

My solution: Redesign, keeping it simple. My interconnecting beams are not owned by either actor, they're global and can connect from anything to anything, they're always updated unless all connected actors are sleeping.

**Comment by ulteq** [comment]
Not the case anymore.
