### ISSUE TITLE
Got banned 

### ISSUE THREAD

**Issue by Meheh** [RigsOfRods/rigs-of-rods#1288]
I was on at 10:00 at night and I got banned (I was hacked and user is adeadtaco)

**Comment by Michael10055** [comment]
For one, this has nothing to do with RoR itself and should not be on GitHub.

Second, you were banned because of both account IP's and info match, even the registration IP:
![firefox_2017-02-28_19-52-48](https://cloud.githubusercontent.com/assets/11002490/23441311/a19bba32-fdef-11e6-840f-16aa715ca968.png)
![firefox_2017-02-28_19-50-04](https://cloud.githubusercontent.com/assets/11002490/23441314/a3d13f48-fdef-11e6-9cb9-270464d51581.png)
IP's do not lie.

**Comment by only-a-ptr** [comment]
^
