### ISSUE TITLE
Buildsystem: Require MyGUI

### ISSUE THREAD

**Issue by susnux** [RigsOfRods/rigs-of-rods#1291]
I randomly found this bug: When I configure cmake and have not installed MyGUI it works and gives this output:
```
% cmake ..
-- checking for module 'MYGUI'
--   package 'MYGUI' not found
-- MYGUI Enabled:       NO
```

But if you then try to build the package it will fail with this error:
```
[ 50%] Building CXX object source/configurator/CMakeFiles/RoRConfig.dir/conf_file.cpp.o
In file included from ..../rigs-of-rods/source/configurator/conf_file.h:30:0,
                 from ..../rigs-of-rods/source/configurator/conf_file.cpp:28:
...../rigs-of-rods/source/configurator/../main/RoRPrerequisites.h:61:54: fatal error: MyGUI_Prerequest.h: File or directory not found
 #include <MyGUI_Prerequest.h> // Forward declarations
                                                      ^
compilation terminated.
```
I have not looked into this, but it seems that either MyGUI should be required (then cmake should fail if it is not available) or the MyGUI part should be made optional.

**Comment by only-a-ptr** [comment]
@susnux Thanks for reporting this.

Truth is, I'm not sure what to do with the `USE_MYGUI` option. It's historical and predates my leadership of the project (versions 0.4.0.7+). It seems useless because RoR is not usable without GUI - the maximum you could do is to load map+vehicle via commandline and then terminate program. It made sense in 0.3x era when limited build of RoR was run on the webserver to test/evaluate/screenshot mods in repository.

@Michael10055 @AnotherFoxGuy @Speciesx @tritonas00 @susnux How about I just remove the option altogether?

**Comment by tritonas00** [comment]
> How about I just remove the option altogether?

Fine with me.

**Comment by Speciesx** [comment]
Since it's useless, you can remove it.

**Comment by Michael10055** [comment]
Agreed. 👍
