### ISSUE TITLE
Can not input wheel?

### ISSUE THREAD

**Issue by Meheh** [RigsOfRods/rigs-of-rods#1294]
I plug my wheel in (usb) and I cant input it? :(

**Comment by disloyalpick** [comment]
Ummm. How about some more information. How are you trying to "input" it?

OS? RoR Version? What wheel?

**Comment by Meheh** [comment]
Windows 10, 0.4.0.7 HORI Apex Wheel PC/PS4/PS3, and I'm trying to like make the wheel work on RoR

**Comment by LNFWebsite** [comment]
There's more information in the http://docs.rigsofrods.org/gameplay/controls-config/ page...

Essentially, you have to write an input mapping for your controller. It's not as hard as it seems (took me a little trial and error finding out the directions of axis' and such)...

The input mapping is a file named `input.map` in your `My Documents/Rigs Of Rods 0.4/config` directory.

Take a look at the other mappings in there and see if they work (rename them to `input.map`), otherwise write one yourself...

Best of luck!
