### ISSUE TITLE
Fixed Pipeline=Enabled Causes RoR to crash after launching RoR

### ISSUE THREAD

**Issue by disloyalpick** [RigsOfRods/rigs-of-rods#1297]
Title says it all

Steps to reproduce...

1. Go to Render Subsystem settings under Direct3D9 and Switch Fixed Render Pipeline to "NO"

2. Launch RoR.

3. Crash RoR. 

Not sure what its purpose is, but I just thought I would report.

![m6pv0u8](https://cloud.githubusercontent.com/assets/13305403/23887987/b312b31c-085b-11e7-8534-61da7731825f.png)

**Comment by only-a-ptr** [comment]
🤣 Nice catch, thanks for reporting.

The "Fixed Render Pipeline" switch essentially disables old-style built-in rendering capabilities of the graphics card/driver and forces the application to submit custom shaders for everything. Recommended reading: https://gamedevelopment.tutsplus.com/articles/the-end-of-fixed-function-rendering-pipelines-and-how-to-move-on--cms-21469

This crash itself is caused by missing file "MyGUI_VP.glsles", which is interesting. Apparently MyGUI has it's own shaders for the case of disabled "Fixed Render Pipeline", and RoR doesn't ship those.
