### ISSUE TITLE
"-userpath" command-line option ignored/Intergate into RoRConfig

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1309]
RoR has a `-userpath` command-line option that will force RoR to use the directory specified instead of the default `Documents/Rigs of Rods 0.4` directory. Very useful if you want to have it on another hard drive or if you need to test using a fresh folder.

On 0.4.7.0 and the latest master however, this option seems to be ignored. RoR just launches normally.
I created a batch script a while back that would let me use a separate user folder for 0.4..6.0/0.4.0.7:
```
@echo off
set PATH=%PATH%;C:\Program Files (x86)\Rigs of Rods 0.4.6\
RoR.exe -userpath E:\path\to\userfolder\
exit
```
It works flawlessly on those versions.

It would also be very useful if RoRConfig supported the same option as you have to edit `RoR.cfg` manually to change settings.

**Comment by only-a-ptr** [comment]
My bad... When I introduced the concept of GVars, I forgot to update this option.

What RoR respects as userdir: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/Application.h#L164

Where the option ends up: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/utils/Settings.cpp#L295

IMO RoR should really support a portable mode: when you put a paths-configuration file in the program directory, paths (possibly relative) are taken from there instead of detecting.

**Comment by AnotherFoxGuy** [comment]
No RoRConfig anymore

**Comment by ulteq** [comment]
> No RoRConfig anymore

That doesn't mean that the `-userpath` approach is wrong, though.
