### ISSUE TITLE
Some add_animation events ignored

### ISSUE THREAD

**Issue by Aivar-RoR** [RigsOfRods/rigs-of-rods#132]
When add_animation in props has a commands_x event, it is ignored by the new truck parser.

>props
45,148,146, 0.14, 0.78,0, 0,0,0, fs65-fanswitch.mesh
add_animation 20,0,0, source: event, mode:x-rotation, eventlock, event:commands_10

An example from the log:
>14:59:25: Mesh: Loading fs65-fanswitch.mesh.
14:59:25: unknown event (ignored): commands_10
14:59:25: == RigSpawner: ERROR (Keyword props) Unknown animation event: commands_10

The events that are ignored are all valid: http://www.rigsofrods.com/wiki/pages/Keypress_Events

The event is still ignored when commands_10 is changed to COMMANDS_10

Vehicle used: Freightliner FS-65 from http://www.rigsofrods.com/repository/view/5226

**Comment by graysonk95** [comment]
This bug might be related, but I managed to get an add_animation rotation usually triggered by F10 to open with Ctrl+4.
I mashed a bunch of other key combinations but only Ctrl+4 made one of the animations work. All of the F-keys did nothing.
It seems like the controls might be messed up. Ctrl+4 is supposed to turn on some flares, but instead it opened this door:
![Uploading screenshot_465.png . . .]()

I haven't been able to replicate this behavior with any other vehicles yet.

**Comment by graysonk95** [comment]
I just rediscovered this issue in 0.4.5.1 in my HDX development and found that the only issue is that the keypress events are case sensitive and ALSO space sensitive.
(My previous bug with Ctrl+4 is not able to be recreated).

Prior to 0.4.5.0, "commands_05" was a valid keypressevent, but it is now ignored by the parser.
18:57:12: Mesh: Loading HDX95_hatchstrut.mesh.
18:57:12: unknown event (ignored): commands_05
18:57:12:  == RigSpawner: ERROR (Keyword props) Unknown animation event: commands_05

Also, prior to 0.4.5.0 " COMMANDS_05" was acceptable. That is, having a space between "event:" and "COMMANDS_05". Now it is also ignored by the parser (notice the extra space).
18:59:11: Mesh: Loading CB95orangerocker.mesh.
18:59:11: unknown event (ignored):  COMMANDS_05
18:59:11:  == RigSpawner: ERROR (Keyword props) Unknown animation event:  COMMANDS_05


Changing it from "event: commands_05" to "event:COMMANDS_05" fixes the issue completely.
The extra space is likely the issue Aivar is experiencing.
The syntax on the Wiki specifically shows a space between "event:" and your keypressevent, so effectively all "source: event" animations are now broken for this reason.
Additionally, since the old parser was more lax, older vehicles with sloppy syntax have broken animations due to case sensitivity, but also the space.

I am currently on Windows 8.1 and do not have RoR working on any Linux distributions to see if the case sensitivity is specific to Windows.

**Comment by only-a-ptr** [comment]
Whitespace. Right. Sorry about that :blush:
