### ISSUE TITLE
debug build in options

### ISSUE THREAD

**Issue by fidoj** [RigsOfRods/rigs-of-rods#1337]
releasewithdebuginfo isnt capable of being used to debug.
im not a programmer. but id like to help debug the code and find errors.
i have located the parts of the code that are related to some graphical problems,
disabling a few lines stops the graphical error, but im unable to explore it and find the root cause.
but i cant set stop points with relwithdebug.

**Comment by Hiradur** [comment]
Debug builds for Windows are disable here: https://github.com/RigsOfRods/rigs-of-rods/blob/master/CMakeLists.txt#L7

I don't know why. I'd add them back in and see what happens.

**Comment by only-a-ptr** [comment]
@fidoj First off, thanks for trying to help.

However, if you can't set breakpoints, then the problem is elsewhere. In VisualStudio, you can set breakpoints under any configuration, except under Release, some may jump to different lines and some variables can be optimized out, thus unreadable.

I'm using VisualStudio 2015 (Windows 7) and I debug under RelWithDebInfo - it's configured to disable all optimizations and set the `/DEBUG` parameter, so AFAIK it's perfectly equivalent to Debug, except it can still be linked to dependencies built as Release or RelWithDebInfo. Dependencies are AFAIK the reason Debug is disabled - our dep package cannot be entirely built as Debug (I don't recall what's the issue...) and mixing build configurations isn't possible, VisualStudio will hurl.

What OS + toolset are you using? And what's the gfx problem you're fixing?
