### ISSUE TITLE
Ability to change cinecam node weight

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1352]
This was brought up since we're doing a lightweight vehicle challenge. 
The cinecam node weight seems to be hardcoded at 20kg (as found [here](https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/Beam.cpp#L921) by @disloyalpick)  and cannot be changed using `set_node_defaults`. It should be possible to change the weight of the cinecam node.

**Comment by disloyalpick** [comment]
The ability to change the weight of it would be great. If I knew how to edit the code to make a customizable, I would. Lol

**Comment by Michael10055** [comment]
I changed the weight to 1kg as a test, using Charger's n/b:
![ror_2017-07-12_12-43-10](https://user-images.githubusercontent.com/11002490/28129233-97dc12a6-6700-11e7-9651-c7ccd48c2c64.png)
Of course, this change breaks all other mods since they're tuned to have the weight set to 20kg.

**Comment by disloyalpick** [comment]
As long as it is tuneable via set_node_defaults it should not break any other mods. We could leave it as 20KG default weight.

Without using a set_node_defaults line the cinecam node will default to the 20KG and thus not break a single mod.

**Comment by Michael10055** [comment]
We could also add another option to the cinecam section. Defaults to 20kg if no option is present.

**Comment by only-a-ptr** [comment]
[ 🎶 Schools out for summer 🎵 ](https://www.youtube.com/watch?v=JpM6_EBQoLs&feature=youtu.be&t=44s) 😆 

I don't recall ever seeing so much activity around here 👍 

Anyway, good spot, it's really hardcoded for reasons unknown - it pre-dates our development history. Anyway, @disloyalpick 's suggestion would definitely break mods because they already use `set_beam_defaults` all over the place and they don't expect it to affect the cinecam. However, @Michael10055 's suggestion sounds just fine.
