### ISSUE TITLE
skeleton view shouldn't be reflected 

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1376]
![ror_2017_09_11_18_41_56_267](https://user-images.githubusercontent.com/1196375/30286455-ec9f5554-9721-11e7-927b-a77cadf849a6.jpg)
![ror_2017_09_11_18_41_53_783](https://user-images.githubusercontent.com/1196375/30286456-eca1854a-9721-11e7-855e-23aad7783897.jpg)
![ror_2017_09_11_18_42_01_218](https://user-images.githubusercontent.com/1196375/30286453-ec9020b6-9721-11e7-8e00-8a04a86ee7c8.jpg)
![ror_2017_09_11_18_43_10_719](https://user-images.githubusercontent.com/1196375/30286454-ec9663cc-9721-11e7-9222-8134ecae5d6c.jpg)

**Comment by LewisGazzard2017** [comment]
Easy fix, thanks for reporting.

**Comment by only-a-ptr** [comment]
> @LewisGazzard2017 Easy fix, thanks for reporting.

You sound very confident 😏 

There are 2 ways to fix this:
* Wait until https://github.com/RigsOfRods/rigs-of-rods/pull/1333 gets merged - it completely remakes the skeletonview: https://github.com/RigsOfRods/rigs-of-rods/pull/1333#issuecomment-309248033 - works in a different way, doesn't get involved in the rendered scene.
* Check & remove the skeletonview from scene when reflections are rendered. Quick and easy but not worth doing since the skeletonview code is about to be removed.

**Comment by Speciesx** [comment]
Fixed in master
