### ISSUE TITLE
[.truck section request]

### ISSUE THREAD

**Issue by disloyalpick** [RigsOfRods/rigs-of-rods#1408]
So I just had this though and I think it is something that will make engine tuning a bit easier.

Something like "Speed Per Gear"

Here is a layout I think might work

GearSpeed
; Number of gears defined in engine section, 1st gear max speed, 2nd gear max speed, 3rd gear max,
 <<options  speed ETC.
 speeds should probably be in meters/sec like the Speedlimiter section already available, but that only limits the vehicle's top speed. But for now I'm just going to write mile/hour speeds. But you get the drift(I think, lol.
5, 30, 60, 90, 120, 140, (last parameter can be options. I'm not sure what options could be but let's brainstorm a bit here.)

This section could work in conjunction with the Speedlimiter section, to extremely and very accurately simulate the tops speeds in each gear if one were to find information for a vehicle they are making in RoR.

**Comment by only-a-ptr** [comment]
> Something like "Speed Per Gear"

This is RoR, not NeedForSpeed 😆 What you're suggesting doesn't make any sense in a context of RoR's physics simulation. Our vehicles are softbody objects which move because torque is applied to their wheels and the wheels have meaningful grip (friction) and vehicle has acceptable aerodynamic properties (wings, fusedrag). How would RoR figure any of this out if you just defined "Me wants car driving 100kph at 3rd gear"?

Of course, there's a lot that could be done to help modders tuning their vehicle's speed. The existing truckfile sections (engine, engoption, engturbo, torquecurve, wings, fusedrag) could be editable in-game via some new GUI. The torquecurve should have a live preview. I'm still planning to equip RoR with a built-in vehicle editor, but to do that, I need to at least finish this: https://github.com/RigsOfRods/rigs-of-rods/pull/1333 - or simplify it and submit it earlier. So much work to be done here.

**Comment by only-a-ptr** [comment]
Closing this as the initial idea was dismissed and I don't think any new truckfile features would help much - RigEditor and tuning GUI is the way to go.
