### ISSUE TITLE
Lost truckfile features

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#1438]
While cleaning up code I noticed some truckfile features somehow disappeared - the data are still present, but there's no code to process them:
* [rollon](http://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#rollon) - This option is dead. I don't know when it died or how the physics handle self-collision ATM.
* [SlopeBrake](http://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#slopebrake) - again, I dunno why or when it died.

I'll investigate further.

**Comment by graysonk95** [comment]
Slopebrake was a workaround from the tdev days ~0.38(?) when something changed causing wheels to slide around on uneven surfaces.

> This section fixes the bug, where trucks slowly roll down a slope no matter how much brake-force is applied.

IIRC, the sliding issue was corrected at some point (maybe in conjunction with terrn2 upgrades) and slopebrake is no longer needed. Can anyone else confirm the bug is gone?

**Comment by ulteq** [comment]
`slopebrake` is gone for good. No longer needed.
