### ISSUE TITLE
RoR game crashes when i try and connect to Multiplayer

### ISSUE THREAD

**Issue by rizicks** [RigsOfRods/rigs-of-rods#1439]
![capture](https://user-images.githubusercontent.com/26100468/34646855-2a67f156-f330-11e7-8211-b9b382ba583e.PNG)
This is the only info I got as of right now.

**Comment by only-a-ptr** [comment]
Hello @rizicks 
Thanks for the screenshot, it shows a lot. The message indicates a problem with your graphics card or drivers. Please post RoR.log (it's in MyDocuments\Rigs of Rods 0.4\logs) so that I can look deeper.

The reason you're getting the crash when joining multiplayer is that some content used in the game (terrain, vehicle, load...) triggers it. Make sure the map used by the MP server loads OK in singleplayer. Then try removing all vehicles from your {MyDocuments\Rigs of Rods 0.4\vehicles} folder and join the server again.

**Comment by rizicks** [comment]
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/1613010/RoR.log)
And yeah, I will try that.

**Comment by rizicks** [comment]
well that didn't work.

**Comment by only-a-ptr** [comment]
> well that didn't work.

Please try again and post RoR.log immediately afterwards. The file is rewritten each time you start RoR. For this reason the RoR.log you posted earlier doesn't help because it's from a different session (singleplayer without problems).

Sorry for not explaining earlier.
