### ISSUE TITLE
tracking videocamera crashes the game

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1529]
Copying from https://github.com/RigsOfRods/rigs-of-rods/issues/1008#issuecomment-307080609

Loading the first vehicle (2012 Saf-T-Liner HDX) from the link below crashes the current master: https://pastebin.com/4BaZKCzt

The fps version 2012 Saf-T-Liner HDX (FPS) works fine

https://www.dropbox.com/s/3clcpvol3jxm80b/a4f210f9f88e78ccaf4cac3a51d7c114b1d78ff1_HDX5.19.12b.zip?dl=1

It worked fine before #1271

**Comment by Michael10055** [comment]
It's caused by the videocamera materials being defined in the `managedmaterials` section instead of a `.material` file.

Commenting out the 2 lines from the `managedmaterials` section and creating a `.material` file for them fixes it.
```
material HDXlmirror_video-camera1
{
    technique
    {
       pass
        {
          texture_unit
          {
            texture video-screen-disabled.png
          }
       }   
    }
}
material HDXlmirror_video-camera2
{
    technique
    {
       pass
        {
          texture_unit
          {
            texture video-screen-disabled.png
          }
       }   
    }
}
```
![image](https://user-images.githubusercontent.com/11002490/42730928-92e3b65e-87d0-11e8-995d-d8639352dd34.png)

**Comment by tritonas00** [comment]
Awesome!
