### ISSUE TITLE
Train Valley: rail switches are broken

### ISSUE THREAD

**Issue by skybon** [RigsOfRods/rigs-of-rods#160]
The game crashes from time to time while driving over a rail switch collision mesh. Happens more frequently with ALP-45DP train (high speed?) and multithreading on (unsure). Disabling inter-vehicle collisions disables the switches and the crashes.
[Debug log](http://pastebin.com/Yt1i73Eb)

**Comment by Hiradur** [comment]
This issue exists since 0.4.0.7 or a bit longer (according to sputnik_1's debug attachments: http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1307247&viewfull=1#post1307247). 
So it's not parser related (though the misplacement of switches may be). Would be great if someone could check if they were already misplaced in 0.4.0.7. Linux port of 0.4.0.7 here: http://sourceforge.net/u/hiradur/rigsofrods/ci/default/tree/

I had quick look at this part of the code but it's not easy to understand. It'll need a more thorough look. I'll keep an eye on this but want to fix some other stuff first.

**Comment by skybon** [comment]
The displacement part has seemingly disappeared, both for FPS and manual switches. Crashes are still there and trains may get stuck on passing through the switches.

**Comment by skybon** [comment]
Also note that trains always crash on *exit* from the switch section,

**Comment by skybon** [comment]
With select rail switches crash happen more often with others. See below:
http://i.imgur.com/6Dtijx4.jpg
http://images.vfl.ru/ii/1439024797/cf20ada4/9512556.png

Note that the crashes happen only *on exit* and if driving *straight ahead*. Making a turn to left or right has not yielded any segfaults so far.

**Comment by skybon** [comment]
Fixed by #405.
