### ISSUE TITLE
skeletonview bugs

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1615]
skeletonview overlapping everything like player, models, GUI, etc.
![ror_2018_10_06_22_28_25_114](https://user-images.githubusercontent.com/1196375/46575567-df753a00-c9b7-11e8-839e-5745ca2e704a.jpg)

![ror_2018_10_07_12_01_20_189](https://user-images.githubusercontent.com/1196375/46580634-dff9e900-ca28-11e8-9433-29463a457f2a.jpg)

spawn 3 vehicles, activate skeletonview at 1, 2 and in 3
![2jjrox](https://user-images.githubusercontent.com/1196375/46575628-fec09700-c9b8-11e8-9ec5-dbf1d20b6749.gif)

skeletonview should extended to all locked and secured loads and vehicles.

![ror_2018_10_06_22_56_56_388](https://user-images.githubusercontent.com/1196375/46575741-6c6dc280-c9bb-11e8-9a3f-874de6784993.jpg)

**Comment by only-a-ptr** [comment]
The new skeletonview is drawn via DearIMGUI, that's why it overlaps everything. I'd consider that a feature rather than a bug tho - it's a diagnostic function, not an effect. And it would complicate programming, too.

**Comment by ulteq** [comment]
> skeletonview overlapping everything like player, models, GUI, etc.

I guess it would make sense to have both the new and the old skeleton view available.

**Comment by only-a-ptr** [comment]
@ulteq > I guess it would make sense to have both the new and the old skeleton view available.

That would be a tragic misunderstanding of the feature and duplication of work.

First of, I don't understand why the overlapping of scene meshes matters at all - it's perfect for diagnostic work, nothing disrupts your view and no extra fading/transparency/camera movement logic is required. Overlapping GUI is a problem, but that can be fixed by DearIMGUI feature called "channels".

Second, you guys probably need a semi-artistic visualization of the flexbody, for purpose of showcasing the physics (screenshots, videos...). That's perfectly OK as long as it's not mistaken for an actual diagnostic tool.
