### ISSUE TITLE
leaving trains on load spawner causing performance drops

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1627]
https://youtu.be/Hhvves64D5Y
https://youtu.be/BDFebwbMzO8

Terrain
https://forum.rigsofrods.org/downloads.php?do=file&id=109
Trains
https://forum.rigsofrods.org/downloads.php?do=file&id=189
https://forum.rigsofrods.org/downloads.php?do=file&id=188

**Comment by only-a-ptr** [comment]
This is most definitely caused by scripting, specifically firing the "character is on spawner!" event. There's already a good deal of hackery and sorry comments in the code related to this.

Actually I'm a bit surprised you don't end up in an endless loop of displaying the Selector GUI. That's how I ended up getting out from Agora bus on Load spawner in Auriga.

**Comment by vido89** [comment]
Im not sure that we should stick "hackey" code around and support it beyond some point in time.
Second thing: I did sitting animation along with other animations should we have more that one animation in sitting pose since we have truck, train, car and airplane ?

**Comment by only-a-ptr** [comment]
@vido89 > Im not sure that we should stick "hackey" code around

I'm already scheming to get rid of it: https://github.com/RigsOfRods/rigs-of-rods/issues/1558

@vido89 > Second thing

Offtopic, start an issue ticket or thread in Dev forum

**Comment by ulteq** [comment]
> This is most definitely caused by scripting

Yes it is caused by this logic: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/collision/Collisions.cpp#L788-L793

Which fails on overlapping collision boxes.

**Comment by only-a-ptr** [comment]
@ulteq Exactly. We need to use something like `std::unordered_set<int> m_occupied_collision_boxes`
