### ISSUE TITLE
Invisible vehicles in Multiplayer

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#178]
I realize that it is not a bug when you cannot see another player's car in RoR in MP (if you don't have it), but a nice new feature would be that RoR logs every vehicle spawned in MP (by others) that you don't have, and then locates that vehicle on the repository or whatever. Then you could download that car and it wouldn't be invisible anymore.

**Comment by Max98** [comment]
What if the user made that vehicle and it's not in the repository?
My idea would be to send only the nodes and beams data to all players and then just update their animations so the players can at least see what's going on.

**Comment by Hiradur** [comment]
I thought about the idea of searching the repo for other people's vehicles myself. I think it should not be auto-download because it would increase traffic of the repository for vehicles you may not want. But it would be could if their was a button to download the vehicle if it's found in the repo.

@Max98 Sending n/b structures probably produces too much traffic, see my simplified calculation here: http://www.rigsofrods.com/wiki/pages/Programmers_%26_Projects#server_side_physics_calculation

**Comment by Max98** [comment]
@Hiradur 
I mean, a truck file, with just the basics things, like wheels and n/b would be around 15kb so that's nothing. There would be a thread working in the background of the receivers and the senders. And as soon as someone doesn't have it, the modded truck file (just n/bs & wheels) would be uploaded somewhere then downloaded by other players, I didn't say that each client will calculate on his own, calculation would be done as for normal vehicles.

**Comment by Hiradur** [comment]
@Max98 How do you want to keep it in sync?

**Comment by Max98** [comment]
The physics you mean? The same way normal vehicles are kept in sync?

**Comment by Hiradur** [comment]
Yeah right, for some reason I mixed up things.

**Comment by Hiradur** [comment]
There's still another problem though. What if the owner does not want the n/b structure to be sent? E.g. he is beta testing or doesn't want to release to the public.

**Comment by graysonk95** [comment]
How about just a translucent mesh in the rough shape of a car that tracks the invisible vehicle?
That way betas/unreleased vehicles are protected, but everyone can still see where they are.

If I saw just an n/b driving around, I'd be worried something is wrong with a mod I have installed.

**Comment by Hiradur** [comment]
It would still be leaking the n/b structure which others could potentially steal to base their own mesh on.
I like the idea of the mesh though. Should be possible.

**Comment by Max98** [comment]
We can just store the temporary n/b structures somewhere and encrypt them so it's just readable by the game.

**Comment by gigapouch** [comment]
I agree.
