### ISSUE TITLE
Missing texture result in crashes

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1878]
![2](https://user-images.githubusercontent.com/1196375/49690519-d11bd980-fb32-11e8-9e28-8b6de3ee19e1.PNG)

Happen with terrains and vehicles like Greece, Mudfest etc.

**Comment by ulteq** [comment]
Doesn't crash on Linux.

**Comment by only-a-ptr** [comment]
I tested on Windows10, x64 Debug build, hardware: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz, Intel(R) HD Graphics 630

Greece: http://archives.rigsofrods.net/repo/files/repofiles-1st-batch/27fee1e0785f52fcdfd15976f5af490cd38ee1f8_LJGreece.zip - Loads fine with both OpenGL and D3d11. I do see `12:46:44: Ogre::FileNotFoundException::FileNotFoundException: Cannot locate resource leak.png in resource group General-Reloaded-1. in ResourceGroupManager::openResource at c:\conan\.conan\data\ogre\1.11.4\anotherfoxguy\stable\build\5c1ecf21b1a7e42880470736b66dce0c0166c1bb\ogremain\src\ogreresourcegroupmanager.cpp (line 704)` in RoR.log but it doesn't get me crashed. However, yesterday I tested on with D3d9 on Win7 and I crashed, but due to some other related issue. I guess this is D3dp specific.

**Comment by only-a-ptr** [comment]
@Speciesx Direct3D11 (DirectX11). My test build refused to load D3D9 renderer for some reason, I'll test that one later.

**Comment by AnotherFoxGuy** [comment]
I never got Direct3D11 working, it crashes immediately on startup

**Comment by tritonas00** [comment]
https://github.com/OGRECave/ogre/pull/1003
