### ISSUE TITLE
Bad Threading Management?

### ISSUE THREAD

**Issue by Max98** [RigsOfRods/rigs-of-rods#220]
After the release of TestBuild 3, few AMD users have noticed a huge performance increase on the AMD FX 6300 using a single vehicle spawned. (http://www.rigsofrods.com/threads/119110-Test-Build-Rigs-of-rods-0-4-5-0-dev?p=1381463&viewfull=1#post1381463)

 I've been discussing with one of them, and I asked him to force the game to use only 3 threads. (NumThreadsInThreadPool in ror.cfg) and yet, his fps increase even more to 172fps rather than 152fps. Maybe the threading mangement isn't doing the job correctly?

**Comment by only-a-ptr** [comment]
Good work tracing the AMD perf issue.

One suspicious area is FlexBody/ThreadPool logic. Each flexbody is a subclass of IThreadTask, and for each frame, it's pushed into task queue in main thread and then processed/removed by ThreadWorkers. https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/Beam.cpp#L3845 This is bad because:
* Popping a task from queue for processing requires locking the queue. Locks are slow.
* It makes no sense to process flexbodies individually - they should be pre-sorted into "Flexbody batches" and assigned to threads directly, Number of flexbodies and their computational cost are known in advance and don't change throughout a lifetime of the vehicle

What we need to pinpoint the AMD problem is a realtime performance graph window showing various stages of simulation processing in various colors. I've already been thinking about this for a while so I'll take a shot at implementing it - the profiling macros from Profiler.h should be fast enough for the job, the window will be toggleable and I'll wrap it all in macros, so we can disable it from compiling if it's too slow.

**Comment by Hiradur** [comment]
The FX6300 only has 3 FPUs while the OS sees it as 6 discrete cores and thinks it has 6 FPUs. So it may produce more threads than the FX6300 can handle simultaneously.

**Comment by Max98** [comment]
I forgot to say, 3 or 6, gives a slightly better fps than 0.

**Comment by Hiradur** [comment]
This could be related to #1 and its fix
