### ISSUE TITLE
Crash with blank material name

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2349]
If a defined material is missing a name, RoR will crash with: ```Ogre::RuntimeAssertionException::RuntimeAssertionException: resourceName is empty string in Ogre::ResourceGroupManager::resourceExistsInAnyGroupImpl at c:\conan\.conan\data\ogre\1.11.5\anotherfoxguy\stable\build\2d13f0c58bafe8a9fae74369aea9c086e652e9f3\ogremain\src\ogreresourcegroupmanager.cpp (line 1635)```

```
material
{
    technique
    {
        pass
        {
        ...
```
Example mod: http://www.austingratzer.com/rigs/downloads.php?do=file&id=479

**Comment by only-a-ptr** [comment]
OGRE docs say material name is required: https://ogrecave.github.io/ogre/api/1.10/_material-_scripts.html#Format

I'm quite sure I can work it around in RoR, but I'll ask Paroj to handle it nicer in OGRE - The script compiler should throw exception "unnamed material" instead of attempting to create it, which triggers an assert in Debug.
