### ISSUE TITLE
Strange tow behaviour in multiplayer

### ISSUE THREAD

**Issue by speccius** [RigsOfRods/rigs-of-rods#2383]
Two identical vehicles latch onto each other (via pressing L to 'tow').
Only one of them can pull the other, not the other way round

**Comment by CuriousMike56** [comment]
This is normal. Node forces aren't transferred over the network, so towing isn't possible and probably never will be.

**Comment by speccius** [comment]
What I don't get is how one person can pull another person, but not the other way around

**Comment by CuriousMike56** [comment]
When you latch onto another vehicle, the connection is only simulated on the client that made the connection. The player you latched onto can pull you since a (almost?) zero-length beam is created between the two points, and the game is trying to keep them connected even though the other node isn't being simulated. To other players, you're essentially just a moving wall.  The only data that gets sent is the node positions.
