### ISSUE TITLE
Client should send a hashed token to race API

### ISSUE THREAD

**Issue by Zentro** [RigsOfRods/rigs-of-rods#2419]
This should be simple.
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/scripting/GameScript.cpp#L791

It should be sending a hashed user token, but it's not.

**Comment by only-a-ptr** [comment]
This is what currently happens:
1. User inputs the naked token to RoR.cfg - loaded as `mp_player_token`
2. User may change `mp_player_token` via MultiplayerSelector GUI
3. When connecting, RoR sends naked token as part of `MSG2_USER_INFO`
4. Script authenticates messages using naked token

I don't know how it originally worked, but since we don't encrypt the communication (do we?), transmitting the token as hashed or naked makes little difference IMO.

**Comment by tritonas00** [comment]
> should RoR.cfg contain the naked or hashed token? 

naked, it is user input

ror does the hashing and sends it
