### ISSUE TITLE
Clarification for flare control numbers

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2551]
With [flares](https://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#flares), you can set a custom activation key using a control number. The control numbers range from 0-500, and `1` would be CTRL+1, `2` would be CTRL+2 and so on, makes sense. However, that page also lists control numbers for other functions:
```
-   `11` Clutch
-   `12` Parking Brake
-   `40` Starter
-   `45` Axle Lock
-   `55` Steer right
-   `56` Steer left
-   `65` Hide GUI
```
This list is small and some don't make much sense for flares (hide GUI). I can't seem to find where in the code these control numbers are defined. That leads me to the following two questions:
1. How *exactly* do control numbers work (from a developer's perspective)?
2. Are there any other control numbers which aren't documented?

Would be nice if flares accepted a [keypress event](https://docs.rigsofrods.org/gameplay/controls-config/#keypress-events), similar to [add_animation](https://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#add_animation).

**Comment by only-a-ptr** [comment]
> How exactly do control numbers work (from a developer's perspective)?

Technical overview: https://github.com/RigsOfRods/rigs-of-rods/issues/2664#issuecomment-780624727
The gist:
* We have 10 input events: EV_TRUCK_LIGHTTOGGLE01 (ctrl+1) ... EV_TRUCK_LIGHTTOGGLE10 (ctrl + 0)
* Control numbers reference these input events: 1 is EV_TRUCK_LIGHTTOGGLE01 ... 10 is EV_TRUCK_LIGHTTOGGLE10
* Using any other control number is a hazzard. RoR is unfortunately coded to support it: it will reference _some_ input event by it's internal numeric value, but this is unstable because adding/removing events will change their numeric values. The '500' limit in docs is sheer nonsense, I have no clue who/why wrote that. The example values, if ever worked, are 10+years out of date. At present, values 10-44 would _"work"_, but I will eliminate that at earliest convenience because it's evil.

> Are there any other control numbers which aren't documented?

Documentation is broken; only 1-10 should be used, ever.

> Would be nice if flares accepted a keypress event, similar to add_animation.

That would be ideal, yes.

**Comment by tritonas00** [comment]
Closing as clarified
https://github.com/RigsOfRods/rigs-of-rods/issues/2551#issuecomment-788797197
https://github.com/RigsOfRods/rigs-of-rods/issues/2664#issuecomment-780624727
https://github.com/RigsOfRods/rigs-of-rods/issues/2664#issuecomment-788797829
