### ISSUE TITLE
MP player name with special character appear blank on the player head.

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#2622]
![image](https://user-images.githubusercontent.com/16364065/98841592-55a9bd80-2416-11eb-9a97-8b8a3f87bd51.png)

**Comment by only-a-ptr** [comment]
Problem identified: RoR correctly keeps the nickname in utf8 'Français' but tries to render it as narrow-text, so the utf8 'ç' (0xC3 0xA7) ([source](https://www.compart.com/en/unicode/U+00E7)) become 2 narrow text characters 'Ã' and '§' ([source](https://en.wikipedia.org/wiki/ISO/IEC_8859-1#Code_page_layout)) but they end up as empty space because the're left out from the used fontdef (see "highcontrast_black" in file "resources/OgreCore/higcontrast.fontdef")
