### ISSUE TITLE
Ability to see user controlled flares in multiplayer

### ISSUE THREAD

**Issue by WillMichals** [RigsOfRods/rigs-of-rods#2664]
I'm posting this here because it has been a good while since this issue has been addressed on the git. 

Why limit the amount of user controlled flares on multiplayer? If my assumption is correct, multiplayer displays the first 2 user controlled flares defined, then nothing else. If the ability is already there, why not extend it out to be able to see x amount (a reasonable quantity) of user controlled flares? Why limit it to just 2? Performance?

**Comment by only-a-ptr** [comment]
Re-opening because I want to deal with this, it came up several times already and I see no reason to not implement this properly. I'm not aware of any "first 2 user controlled flares" limitation. Let's see (making notes as I go):
* our input system recognizes 10 user lights: https://github.com/RigsOfRods/rigs-of-rods/blob/dd827ff981e0f712a4cf28d326bb2e9b67bcdac1/source/main/utils/InputEngine.cpp#L129-L138. This is OK.
* input events are processed here: https://github.com/RigsOfRods/rigs-of-rods/blob/dd827ff981e0f712a4cf28d326bb2e9b67bcdac1/source/main/physics/Actor.cpp#L3020, using user-defined "control number" from truck file. This would be OK if the control number was limited to 1-10.
* Documentation states the control number can be 1-500. That's pure evil. Technically, numbers 10-44 would somewhat work but only by accidentally mapping to these fields (notice they're after the userflares): https://github.com/RigsOfRods/rigs-of-rods/blob/dd827ff981e0f712a4cf28d326bb2e9b67bcdac1/source/main/utils/InputEngine.h#L304-L357. The order of the elements can change at developer's convenience.
* RoRnet reserves 4 bits for custom flares: https://github.com/RigsOfRods/rigs-of-rods/blob/dd827ff981e0f712a4cf28d326bb2e9b67bcdac1/source/main/network/RoRnet.h#L89-L92, it doesn't seem like a big deal to use more.
* How sending net data works: The spawner records the flare-IDs of the first 4 custom lights in `Actor::m_net_custom_lights`, and `Actor::sendStreamData()`, uses `getCustomLightVisible()` to query 'm_net_custom_lights' and set the RoRnet's light bits accordingly. https://github.com/RigsOfRods/rigs-of-rods/blob/dd827ff981e0f712a4cf28d326bb2e9b67bcdac1/source/main/physics/Actor.cpp#L1950-L1959 The code is messy but looks valid.
* How receiving net data works: `Actor::CalcNetwork()` does the inverse of the send process: https://github.com/RigsOfRods/rigs-of-rods/blob/dd827ff981e0f712a4cf28d326bb2e9b67bcdac1/source/main/physics/Actor.cpp#L608-L611. Looks OK.

CONCLUSION:
First 4 custom flares defined in truck file should work over the network. It wouldn't be a big deal to extend RoRnet to send all 10.

CHECKLIST:
* fix the doc and the Validator to only accept control numbers 1-10.
* (future) improve truckfile so flares can be toggled/triggered by input event names. Those would be properly (and maintainably) translated to input events.

**Comment by tritonas00** [comment]
> I don't know why just 4

probably to save bandwith, but after ulteq's net rewrite should not be an issue

**Comment by WillMichals** [comment]
> It wouldn't be a big deal to extend RoRnet to send all 10

The first 10 defined user flares, or the 10 flare control groups?

In other words, will there be an unlimited amount of flares displayed on each flare group, or 10 flares total?

**Comment by only-a-ptr** [comment]
> @WillMichals The first 10 defined user flares, or the 10 flare control groups?

Very good question. Currently it's the first 4 individual flares, actually. But for the future I'd like all 10 groups to be sent.

**Comment by WillMichals** [comment]
> But for the future I'd like all 10 groups to be sent.

When you extend it, will you extend it to all 10 groups?
I only ask because looking at the pull request frm @tritonas00, it appears that instead of only 4 individual flares, only the first 10 custom individually defined flares are being sent, but I could be wrong.

**Comment by only-a-ptr** [comment]
@WillMichals You're right, in it's current state it would only transmit first 10 individual flares. I already requested change: https://github.com/RigsOfRods/rigs-of-rods/pull/2690#issuecomment-782058913

**Comment by WillMichals** [comment]
Sounds and looks great. Thank you both

**Comment by DarthCainRor** [comment]
The Control numbers above 10 are for the "Custom Controlled" flares. 
![image](https://user-images.githubusercontent.com/10333582/108870100-6f35d600-75bd-11eb-8983-32ec9ec836e1.png) 

https://github.com/RigsOfRods/rigs-of-rods/issues/2551

**Comment by only-a-ptr** [comment]
@DarthCainRor Thanks for the reminder, answered: https://github.com/RigsOfRods/rigs-of-rods/issues/2551#issuecomment-788797197. The takeaway: Doc is broken, only 1-10 should be used, ever.

**Comment by tritonas00** [comment]
it seems we have already an issue for this https://github.com/RigsOfRods/rigs-of-rods/issues/32

custom flares over network will be hopefully addressed soon
