### ISSUE TITLE
Why do you need an account to race?

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#272]
I would like to run my own RoR server (I know how to, I have my own web server and MC server) as well as race in the terrains with my score published, but it says you need an account and I can't make an account because I'm not old enough. Is there a work around to this?

**Comment by Hiradur** [comment]
tdev runs the site and did the programming. We have no admin access to the site so there is nothing that can be done about it at the moment.
However, bundling race times with an account makes sense because it keeps the list clean and prevents people to claim

Imagine you would see this on the best times list:
Xx_Hiradur_xX
Hiradur
Master_Hiradur
Hiradur1337

It looks ugly and there would be no way to be able to tell which of these entries are the authentic Hiradur and who just used the name or if Hiradur just likes to change names for every race.

**Comment by gigapouch** [comment]
OK, I understand.

**Comment by Hiradur** [comment]
Great. Time flies, trust me. ;)

I'll close this issue because there isn't much more to say.
