### ISSUE TITLE
Parts of a vehicle that fall of "teleport" and follow the vehicle instead of staying where it landed. (Online Issue)

### ISSUE THREAD

**Issue by Danny-Werewolf** [RigsOfRods/rigs-of-rods#2783]
Since about 0.4.5, the body parts that fell off did stay where they landed, back in 0.39 and below. Now, when a body part falls off on another person's screen, it will follow them and teleport in a grid, following the truck. It's a bit difficult to explain, but anything will do this if it falls off, even tires. Here's a video that shows how the body part will act when it falls off.

https://youtu.be/2gzDuGPqKms?t=1432

**Comment by only-a-ptr** [comment]
Very good observation, thanks for the report.

This is caused by our network compression scheme added by Ulteq circa 4 years ago. It reduces net. traffic to half but assumes all nodes always stay within a few meters from the physics origin point. If they're further, the numbers wrap around and generate this effect.

But I'm thinking that fallen parts require a smarter approach overall. Currently the game doesn't treat them differently from other nodes, they still remain active and stretch the vehicle's bounding box, which potentially triggers many more collision checks than needed. This would become ever more of a problem if I tried to implement proper multiplayer collisions. If they were separate Actors, they would just go to sleep soon.

Ideas:
* Single player = a part which falls off would become a separate Actor of type NOT_DRIVEABLE and hidden in top menu selector. Nodes, beams, props and flexbodies of the detached part would be migrated to the new Actor, including forces, so nothing would visually change for the player. Flares would automatically shut down. Also, a "detached part (number)" relationship would be estabilished so that the repair hotkey can merge the fallen parts back in. 
* Multiplayer = Same as singleplayer except the detachment must be propataged over network. Specifically, a list of node numbers which detached must be sent - just a detacher group wouldn't be enough, maybe the part broke away without detacher group. From this node list, the remote side would determine beams, props and flexbodies, and modify the Actor like in singleplayer.

This would be involved coding, yes, but it wouldn't take that long to do. I need to think about it.

**Comment by Danny-Werewolf** [comment]
That sounds awesome, so hopefully it'd be implemented sometime soon. Thanks for the reply!
