### ISSUE TITLE
Skinzip file replacing whole material file not working

### ISSUE THREAD

**Issue by DarthCainRor** [RigsOfRods/rigs-of-rods#2824]
So I'm in the process of trying to upload some old mods and their respective skinzips from the old forum when I found something rather curious.

The skinzip files for the FLK-1500, uses the .skin file to replace complete .material files instead of individual material names. In doing so, it causes the skins to no longer work, as this (probably) wasn't an intended use for them, as its something I've not seen before.

How to replicate:

Download [the crane](https://cdn.anotherfoxguy.com/repo-backup/520d339d3ec1d780b1b32955ffa1dd91cf8892e0_Craneman-AIN_002-Rotexx-FLK-1500-tele.zip) and it's [skins](https://cdn.anotherfoxguy.com/repo-backup/43f8f6da7b14a3d4ed9e02eaa34f1fc9122e7d47_FLK_1500_BIG_Skinzip_Pack.zip) (you have to unzip this, as there are many zips inside), you only need to drag one of the skinzips in your mods folder to test

Launch the game and attempt to spawn `AinTech FLK-1500 108m`

No skin selection pops up

What is expected:

Skin selection window pops up
![image](https://user-images.githubusercontent.com/10333582/142573234-a4b8b2e8-8437-47d7-b4f5-b152d3fc5c91.png)

Allows you to load selected vehicle skin.

![image](https://user-images.githubusercontent.com/10333582/142573252-858c34f3-0295-466c-99d9-0553c63f7432.png)

**Comment by DarthCainRor** [comment]
Mentioned this in discord, but it doesn't actually solve the issue, just fixes a parsing error the old mod had.

The same crane skin as above looks like this in game as of now:
![screenshot_2022-03-21_02-04-30_1](https://user-images.githubusercontent.com/10333582/159218165-d4a5b7bf-968f-4ff7-a2bc-374353a4910e.png)

**Comment by only-a-ptr** [comment]
@DarthCainRor 

I looked into several older versions of the source code, all the way to 2009, and I conclude that the skins of this crane could never have worked. To be specific, the `replaceTexture` entries worked, but the `replaceMaterial` entries just had zero effect. Also, all the .skin files I reviewed contained all the same replaceMaterial lines, just different replaceTexture lines, which doesn't make sense to begin with.

One thing that did change is resource management... newer versions will only load texture replacements from the .skinzip, while older versions may have mixed everything together. I suspect your skinzips may contain files with same names but different content which may cause mixups in older versions. Please try merging all the skins to single .skinzip so that equivalent files cancel each other, then try loading one specific skin and verify that the visible textures match what the .skin is actually referencing.
