### ISSUE TITLE
[request] "shifterlin" animation source addition

### ISSUE THREAD

**Issue by willmichals** [RigsOfRods/rigs-of-rods#2854]
Hi,

Just requesting we get a animation source exactly like `shifterlin` except with no animation for the difference of 1st/2nd/3rd/etc.... - just D/N/R

Perhaps it could be referred to as `autoshifterlin`

Thank you

**Comment by ohlidalp** [comment]
I fixed the glitch - by accident, I was clamping reverse gears instead of forward gears.
I also updated the test mod.
![obrazek](https://github.com/RigsOfRods/rigs-of-rods/assets/491088/531b3887-2138-4f1b-9ff9-cbe1a111b2e3)
[propboard_w_shifter_3078.zip](https://github.com/user-attachments/files/16119212/propboard_w_shifter_3078.zip)
