### ISSUE TITLE
Mod trouble

### ISSUE THREAD

**Issue by Objectedmanx46** [RigsOfRods/rigs-of-rods#2880]
I recently reinstalled rigs of rods and backed up all my mods i re placed them into the game and 40% of the mods are able to load in did i miss a step or did i do something wrong if you need to view my logs i will link the attachment below
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/8318618/RoR.log)

**Comment by jared704** [comment]
Are you installing into the correct directory?

`Documents/My Games/Rigs of Rods/mods`

**Comment by only-a-ptr** [comment]
@Objectedmanx46

Hello, thanks for reporting and posting the log - however, it shows nothing.

First, make sure your mods are in `Documents\My Games\Rigs of Rods\mods`.

If your problem is that some mods don't show up in the selector, shut down the game, go to directory `Documents\My Games\Rigs of Rods\cache`, delete file 'mods.cache', start the game. The game will inspect all the mods and build new cache. If this doesn't help, post the RoR.log again.

If your problem is that the mod doesn't load when you pick it in selector, do the cache regen first, then try spawning the mod and if it fails, post the RoR.log of that.

**Comment by Objectedmanx46** [comment]
My problem is that is that some mods don't show up in the selector. I followed the instructions and attempted to do so and it loaded more mods I believe I should have 456 vehicles in the list so do I keep on repeating the step until all the mods that I need are loaded?

**Comment by only-a-ptr** [comment]
@Objectedmanx46 

Sorry about the late response... is this still a problem? If yes, please pinpoint at least one official mod which doesn't show up, remove all others, regen cache and check if it shows up. Also make sure you have "Category: All" selected in the top left dropdown box.

**Comment by only-a-ptr** [comment]
Closing this as stale and probably not relevant anymore.
