### ISSUE TITLE
Flexbody binds to nodes outside 'forset'.

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#2923]
Discord complaint by DannyWerewolf.

If a flexbody is bound to a detachable part and it detaches, the mesh keeps stretching after the vehicle, even though all nodes in the 'forset' have detached.
![obrazek](https://user-images.githubusercontent.com/491088/180332866-e28f9068-a8ff-4f0b-afd5-3d1f1fc09322.png)
![obrazek](https://user-images.githubusercontent.com/491088/180332885-d5ec1a84-fbae-415b-9bf5-fd166435ef7b.png)
![obrazek](https://user-images.githubusercontent.com/491088/180332813-e30eed6d-3d97-489c-aa58-2600c4ea573b.png)

it's probably because the flexbody binds 3 nodes for each vertex: reference, X and Y, and only the reference nodes are taken from the forset, while the X/Y nodes are searched by distance.

Danny Werewolf has a feeling that it's not a specific node but the center of the truck.

**Comment by DarthCainRor** [comment]
Is his ror.log giving flexbody errors? 

I'm fairly certain this happens when a flexbody has been defined using too few nodes as references. I believe it used to be documented somewhere, but flexbodies require either 8 or 10 nodes to work, and not give errors/stretch, because they're looking for other nodes.
