### ISSUE TITLE
Minimap player location doesn't update

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#295]
Looking at the map when you press Tab, you have to open the map again to update your location on it.

**Comment by ulteq** [comment]
> Looking at the map when you press Tab, you have to open the map again to update your location on it.

Not the case for me (Linux with Ogre 1.9).

**Comment by Hiradur** [comment]
> Not the case for me (Linux with Ogre 1.9).

Really? I don't see any indicators on the minimap at all (Linux with Ogre 1.9).

**Comment by ulteq** [comment]
> I don't see any indicators on the minimap at all

The icons only appear on the main map and require manual activation:
https://github.com/RigsOfRods/rigs-of-rods/blob/master/bin/resources/skeleton/config/input.map#L204

See: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/terrain/map/SurveyMapManager.cpp#L44

The reason behind this was that they are not aligned properly if you zoom the map.

However, this is a questionable reason, because you can not zoom the main map.

**Comment by AnotherFoxGuy** [comment]
you can zoom the map by setting the overview map to zoom in the guisettings
```
guisettings
interactiveOverviewMap zoom
 ```
http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Guisettings

**Comment by ulteq** [comment]
So, can we close this?
