### ISSUE TITLE
Connected actors no longer grouped 

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#3067]
From #development channel on Discord:
> it seems actor grouping is broken on master, when pressing 'end' key to pause actor physics, it should also pause physics for any trailers/loads attached (2022.12 screenshot)
![image](https://github.com/RigsOfRods/rigs-of-rods/assets/46073351/278fe3a7-5e33-46dd-9360-7e3cea07a038)
but now it doesn't
![image](https://github.com/RigsOfRods/rigs-of-rods/assets/46073351/0886fbfe-f918-4362-8877-43daf206c0b7)

This also means actors are no longer grouped together when using the "soft reset" feature (`COMMON_TOGGLE_RESET_MODE`).

**Comment by only-a-ptr** [comment]
I like the term "actor grouping", presently there is no such mechanic in the code, all syncing between linked actors (lights, brakes, skeletview, etc ...) is done separately.

This issue was most likely introduced with the `MSG_SIM_ACTOR_LINKING_REQUESTED` which was conceived as a multi threading fix
