### ISSUE TITLE
Soundsources3 Not Available Yet

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#31]
This is issue 1008 from the Wiki Bugtracker (http://www.rigsofrods.com/wiki/pages/Bugtracker), I haven't seen any mention of it being fixed, so here is a ticket.

http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Soundsources3

**Comment by only-a-ptr** [comment]
Soundsources3 were never implemented. RoR 0.4.0.7 had some internal support for them, but in the .truck file parser, soundsources3 was just a placeholder keyword.

Right now, the priority is physics and performance. Sound enhancements will come later

**Comment by only-a-ptr** [comment]
Closing this because soundsources3 won't be implemented, see my comment at https://forum.rigsofrods.org/thread-1467-post-11744.html#pid11744

Don't get me wrong - RoR does need a better mechanism to define sounds, but soundsources3 are not the way to go. If you have a comprehensive idea of how sounds should be managed in RoR, open a new ticket about it please.
