### ISSUE TITLE
Camera view breaks when switching vehicles using Menubar->Vehicles menu and having cinecam activated.

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#311]
Load a vehicle, change to cabin view and select now your current vehicle in "Vehicles", this will activate the vehicle GUI in cabin view. Load a second vehicle and change also to cabin view, now change to the other vehicle, this will also activate the vehicle GUI and break the camera view.

**Comment by only-a-ptr** [comment]
@Speciesx Thanks for reporting this one.
Turns out RoR was keeping camera state (including cinecam number) globally, regardless of which vehicle activated them. This caused cinecam-mode to be de-activated in a differrent vehicle that had it activated, and using flawed cinecam numbers.

Fix ready, will be available soon.
