### ISSUE TITLE
Alternative mods folder location

### ISSUE THREAD

**Issue by Night-Fury-SGN** [RigsOfRods/rigs-of-rods#3149]
Some Mods Break being in an alternative mods folder location, it happens on the main dev build and this fork by only_a_ptr that I'm running

https://github.com/RigsOfRods/rigs-of-rods/assets/82725929/c340865c-2492-466f-9c7d-16a757d1e687

**Comment by CuriousMike56** [comment]
Please upload your RoR.log file (from `Documents\My Games\Rigs of Rods\logs`) after receiving the spawn error.

**Comment by Night-Fury-SGN** [comment]
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/14895785/RoR.log)

**Comment by Lepes** [comment]
I can confirm this error on extra mods folder and you will only get this error on linux running RoR from a terminal command line: "./RunRoR" since RoR.log is clean.

I "fix" sometimes this error by removing any space in the name of the zip, (or folder if it was unzipped) and in the name of trucks or trailers that contain a space. Then zip it and then you can load it without problems. Sometimes doesn't work and you can not load the vehicle, as it happens for Box5W900.

in RoR.log doesn't appear this line:  "===== LOADING VEHICLE:"  meanwhile you get this on a terminal command line:

Texture 'Box5W900_Box5W900D.truck.mini.dds': Loading 1 faces(PF_DXT1,256x256x1) with 8 custom mipmaps from Image. Internal format is PF_DXT1,256x256x1.
 ===== LOADING VEHICLE: 
[RoR|General|Error] Failed to load 'Box5W900D.truck' (type: 'actor'), message: basic_string::substr: __pos (which is 52) > this->size() (which is 45)
Texture 'error.png': Loading 1 faces(PF_A8R8G8B8,16x16x1) with 4 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,16x16x1.
[RoR|CVar]             sim_state:  "2" (was: "1")
[RoR|CVar]             app_state:  "3" (was: "2")
AL lib: (EE) alc_cleanup: 1 device not closed
free(): invalid pointer
Aborted (core dumped)

**Comment by Night-Fury-SGN** [comment]
@Lepes well I'm running Windows 11 so you could probably say it's not just a Linux problem anymore

**Comment by ohlidalp** [comment]
@Night-Fury-SGN Sorry for the response lag, been busy IRL. Please test the "broken" scenario again with the itch devbuild (or latest master) and post RoR.log of that - the log you posted earlier doesn't show any truck spawning, just entering simple2.terrn2 and then exiting game.

![obrazek](https://github.com/RigsOfRods/rigs-of-rods/assets/491088/cdfa659a-4e55-4391-9d5a-721bfec7c9e2)
I'm baffled by this error because we don't have `"Failed to load {$name} ..."` text anywhere in the code. Same applies to `"... invalid string position"`. I looked both in current master and 2022.12.

Anyway, I got a fresher RoR.log at discord: https://discord.com/channels/136544456244461568/189904947649708032/1256443685533384795
```
21:00:54: [RoR|General|Error] MSG_SIM_LOAD_TERRN_REQUESTED: invalid string position
```
My best guess is that "invalid string position" is an exception thrown by `std::string` (C++ standard library) when the code tries to read something that's not there.
