### ISSUE TITLE
Option to change in-game node debug size

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#328]
Currently the node debug works fine for simple node and beams. However, complex node and beams (Example: gabester's vehicles) have a lot of nodes close together so you can barely read the node numbers. Would be nice to have a setting that allows you to change the size of these numbers.
![screenshot_156](https://cloud.githubusercontent.com/assets/11002490/8843871/61ae469c-30dc-11e5-9f5d-fdd8e8f35486.png)

**Comment by only-a-ptr** [comment]
Besides the obvious problem with unreadability, the node debug view also kills FPS.

The "debug" views need a complete overhaul. Most of them will become unusable/useless after 0.4.5 because:
* The N/B processing speed _will_ be increased by planned optimizations, and thus the number of nodes/beams will increase to a level where debugging like this will be useless.
* The rig editor will be enhanced with grouping/coloring beams, and thus the need for post-debugging in simulation will decrease.

**Comment by Michael10055** [comment]
Closing this as it is fixed in the IMGUI PR: #1333

**Comment by Michael10055** [comment]
Since I don't think the new IMGUI skeleton view will make it into the planned 0.4.8 release, it would be greatly appreciated if the node debug size was changed:
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/Beam.cpp#L4721
Changing `0.5` to `0.05` (same size as 0.36's node debug) is perfect:
`t.node->setScale(Vector3(0.05, 0.05, 0.05));`
![image](https://user-images.githubusercontent.com/11002490/34077227-8d7268cc-e2cc-11e7-92d6-329700887bb8.png)

**Comment by only-a-ptr** [comment]
@Michael10055 Very nice - and since you've already coded and built it, why not make it your first PR?

The remade skeleton view has glitches - it goes haywire when you turn camera away from the vehicle, and it broke display on connected vehicles somehow. I'm not planning to include it in v0.4.8, but I do plan to make the next release a lot sooner than in another year - there's more unfinished stuff that I have lying around.
