### ISSUE TITLE
Tracked vehicles not working correctly.

### ISSUE THREAD

**Issue by DarthCainRor** [RigsOfRods/rigs-of-rods#381]
It appears as if tracked vehicles that use rotators to move slidenodes around the rails, are slightly broken. From what I can see it looks like the submeshes attached to the rotator part are no longer smoothly moving the slidenodes along, causing the tracks to jerk in unrealistic manners.

Vehicles tested with: 
 http://www.rigsofrods.com/threads/115690-Hitachi-EX1200-5?p=1347026&viewfull=1#post1347026

http://www.rigsofrods.com/threads/112719-volvo-EC140C

And a private tracked vehicle I'm working on.

**Comment by Max98** [comment]
Can you try disabling Intra-Collision from RoRConfig->Advanced.

**Comment by DarthCainRor** [comment]
That causes them to not work at all, as it needs to collide to move.

**Comment by Max98** [comment]
Are you sure that you disabled intra and not inter?

**Comment by DarthCainRor** [comment]
![](https://i.gyazo.com/b1931f1835a56ba1b26d0c1fd939cb0a.png)

Quite certain. The way tracks are designed they need intra vehicle collisions. It's how they work. Submeshes are attached to the rotator, with sit between slidenodes and push the nodes along the tracks.

**Comment by DarthCainRor** [comment]
No further comments? :-/ I mean they're definitely not working correctly, and there is no error related to them in the log files. >.<

**Comment by fidoj** [comment]
the error seems to be at the looping part of the slide rails, some of the nodes jump at the intersection causing shaking

**Comment by DarthCainRor** [comment]
any word on this? been working on a few things with tracks, and it'd be nice if they actually worked :-/

**Comment by DarthCainRor** [comment]
I'm still not certain tracked vehicles are operating 100% the same as in .38. I would definitely say they are definitely better now than they were in .4.5, and are semi usuable, but they're still no where near as smooth moving as they used to be.

**Comment by only-a-ptr** [comment]
@DarthCainRor I completely understand your point of view, but fixing this isn't a matter of reverting some particular changes or looking into some specific area of simulation. From a developer's standpoint, the only way to restore 0.38's behavior is to roll back all changes since that version and never touch the code again. Or, we may tune the simulation to get closer to what it was before, but to do that, we need a lot more detailed description of the problem. Please do some more testing and describe what exactly is disturbing you.

RoR's simulation code is a house of madness. There are calculations that we know are broken (normalization), but correcting them breaks some vehicles. The collision system is "optimized" for performance by actually skipping collision tests. And until quite recently, everything was subtly dependent on the framerate. However, modders of 0.38 era somehow tuned their vehicles to work well under these broken conditions. Devs today have 2 options: either carefully observe what the broken simulation does and maintain compatibility (= supper annoying work, we all went thru "why did I even touch it" experience) or try to straighten up the logic a bit and hope nothing breaks noticeably. @ulteq and @mikadou did some really big improvements to the simulation, both regarding performance and sanity, but as I explained, it probably had side effect.

Conclusion: we're doing what we can to keep vehicles working right, but we can't do it by not touching the code - we need to make changes and continuously test if we didn't break anything. Perhaps our test should include tracked vehicles more - what should we use? What should we concentrate at? We need more input from you.

**Comment by DarthCainRor** [comment]
I don't believe I ever stated to revert the code and go back or to not even touch the code at all. I was just adding it's still doing the same thing as when I reported this bug, only it's not as bad as it used to be. Tracked vehicles are semi usable, but they still suffer from the jolting and shuttering I previously reported, because the rotator still seems to be skipping some of the contacter nodes along the slide rails. I only didn't notice this sooner because I don't really "play" RoR, except when I'm taking pictures, or working on one of my mods, of which I recently tried working on my tracked loader/dozer again. The two mods I originally linked are still viable options to use

**Comment by Hiradur** [comment]
> I only didn't notice this sooner because I don't really "play" RoR

Welcome to the club, I think this is something many developers have in common. We (me at least) are noobs at the game which is why we need pointers by experienced players at what to look at.

**Comment by only-a-ptr** [comment]
> We (me at least) are noobs at the game which is why we need pointers by experienced players at what to look at.

My case exactly. My initial idea about RoR was "hey, this could be fun to drive around, if it just worked a little better and had some meaningful tools". So I started coding.

**Comment by ulteq** [comment]
> the rotator still seems to be skipping some of the contacter nodes along the slide rails

It will be very hard to find the reason for it without knowing which commit introduced the bug.

**Comment by DarthCainRor** [comment]
Track Test N/b using rotators: http://www.mediafire.com/file/9d3gcii9mgv69rc/trackNBtest.truck
Track test made by lifter using wheels: http://www.mediafire.com/file/9syw6j1w1wglu77/tracktestv15.zip
