### ISSUE TITLE
RoRBot's teeth show when running

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#400]
Most likely a camera placement issue, but RoRBot's teeth and part of his shirt sometimes appear during sprinting. It happens even more often in Multiplayer.
![screenshot_25](https://cloud.githubusercontent.com/assets/7621364/9265676/954a7a00-41eb-11e5-9aed-61d535231a57.png)

**Comment by Hiradur** [comment]
To solve this we could either
- replace the camera when running -> ugly transition
- change the animation so that the head doesn't move
- don't display RoRBot at all in first person mode

Which do you prefer?

**Comment by DirtGamer301** [comment]
@Hiradur 
I don't know what RoRbots cameras are set up like, but if there's the ability of strengthen it so it doesn't move that much (like in vehicles) you could give that a try.

**Comment by Hiradur** [comment]
@DirtGamer301 The camera would still be fixed (no head bobbing) but if you toggle running on/off there would always be a noticeable jump between camera positions.

**Comment by fidoj** [comment]
I was watching a video on head movement and a neurologist said we don't have head bobbing because our brain normalizes our view and stabilizes what we perceive. So every game that adds bobbing is only confusing our brains natural normalizing.

**Comment by adriansnetlis** [comment]
Maybe attach the camera to the eyes of player? It'd add in bobbing, but would make sure that you see exactly what RoRbot sees.

**Comment by fidoj** [comment]
hows about you read what causes head bobbing and how unrealistic it is. if you read up on this "condition" eye bobbing is related to a disease and unrealistic in healthy humans.

[http://www.neurology.org/content/25/10/949](url)

**Comment by fidoj** [comment]
https://www.reddit.com/r/starcitizen/comments/3b4t2m/head_bob_is_not_cool_fun_realistic_or_any_other/

**Comment by adriansnetlis** [comment]
Yes, I know that brain tries to filter out some of motion to make it easier to navigate, but when you run - your head moves up and down a bit and you can notice it a bit. And here it depends on animations. RoRbot could try to do what brains do - smooth out the movement of the image we see(by smoothing out camera). However, IDK if it's that easy.

**Comment by Hiradur** [comment]
> but when you run - your head moves up and down a bit and you can notice it a bit

I never noticed it and I assume you need to focus on it to notice. I hate head bobbing in video games so I don't think this is a good solution.

**Comment by fidoj** [comment]
neurologists have concluded that you see at around 25 frames per second and that in your entire waking day you only see a portion of that, as most is used for processing not vision, the only reason we use higher frame rate lcd's is because of tearing our brain recognizes the irregularitues we see and marks it as a error we have to see, when you run not only are you moving, but your also shocking your body, your eyes also get compressed and change your vision giving perception of vertical movement that is an error in our eyes during that activity, but i bet if you ask a marathon runner if he notices head bobbing they would say no. head bobbing is unnatural and makes people sick for a reason, its a sign of bad health. i dislike playing games with the head bobbing "animation" yes there might be some instances where its suitable, such as if you where playing a survival game and you get low health blurred bobbing vision would heighten your sense of "death". but rigs of rods is not about being sick, its not about war, its about exploring the sandbox and making things possible. i think there are more important things that need to be accessible be for a user chosen "effect" that 1 in 20 might use.

**Comment by only-a-ptr** [comment]
I'm fairly sure @Vido89's new animations (https://github.com/RigsOfRods/rigs-of-rods/pull/1111) resolved this. If not, I'm sure he can tackle it.
