### ISSUE TITLE
Does not compile with latest angelscript

### ISSUE THREAD

**Issue by anordal** [RigsOfRods/rigs-of-rods#441]
RoR doesn't compile with angelscript 2.29. I got «No conversion from int\* to char**» or something. Installing angelscript 2.22 instead fixed it.

On OpenSuse Tumbleweed, that means installing angelscript_2221-devel instead of angelscript-devel.

Maybe this could be put into the cmake detection script, or just the compilation instructions, as I nearly gave up before finding this out.

**Comment by Hiradur** [comment]
Sorry for the inconvenience. We are aware of this and the required AS version is mentioned here: http://www.rigsofrods.com/wiki/pages/Compiling_3rd_party_libraries#Versions

AS needs to be updated ASAP, also due to #174 

It's on top of my todo list but the PSU of my desktop computer died so at the moment I can't work on it.

**Comment by Hiradur** [comment]
I'm unassigning myself because I don't think I'll have the time and patience to do this anytime soon.

All I can say is that this more complex than the usual dependency upgrade. Fixing compiler errors doesn't seem to be enough. Runtime errors seem to be the real problem here. Some functions may need to be rewritten.
neorej16's attempt to update to AngelScript 2.26.3 may be of help but I don't know what its status is.
https://sourceforge.net/u/neorej16/rigsofrods/commit_browser

**Comment by Hubbitus** [comment]
Compile fixes I have had also made before... It is not so hard and is not also helpful either Unfortunately.

Is there PR of neorej16's attempt of porting?

**Comment by Hiradur** [comment]
The latest attempt to upgrade AS is in this PR: https://github.com/RigsOfRods/rigs-of-rods/pull/999
But fixing compiler errors is not the problem here, the tricky part are the runtime errors.

**Comment by AnotherFoxGuy** [comment]
Fixed in #1373
