### ISSUE TITLE
Bad UTF-8 Continuation type while regenning CACHE

### ISSUE THREAD

**Issue by disloyalpick** [RigsOfRods/rigs-of-rods#455]
I'm not sure which vehicles or stuff is causing this, but I will delete contents of all the log files, and try to clear/regen CACHE and upload the log files for someone to check out.
![ss 2015-11-19 at 02 43 03](https://cloud.githubusercontent.com/assets/13305403/11282179/01cd793e-8ecc-11e5-84b2-02f3641e4bc6.png)

AngleScript.log: http://pastebin.com/9rb2hNFq

ConfigLog.txt: http://pastebin.com/2WgNXuYn

mygui.log: http://pastebin.com/cHSNU6Pc

RoRConfig.log: http://pastebin.com/xw13p3d4

RoR.log(Exceeded pastebin max size limit)   http://puu.sh/lrqiT/166c8fc19f.log

Thank you for taking time to look this over. Due to this I can't even play RoR. Good luck fixing it if you find any problem!!

**Comment by Hiradur** [comment]
Could you check if caboverpete.truck has a similar problem to what is described here: https://github.com/RigsOfRods/rigs-of-rods/issues/364

**Comment by disloyalpick** [comment]
It does

http://puu.sh/lrrfN/2f9f9ac073.png

**Comment by DirtGamer301** [comment]
You can try removing the mail adress, but it's actually supposed to be there so I personally don't think it causes problems.

**Comment by only-a-ptr** [comment]
"@" is an ASCII character, that's not the issue. The problem is somewhere else.

And yes, this is the same problem as https://github.com/RigsOfRods/rigs-of-rods/issues/364

I'm starting to see the issue: I used MyGUI's UStrings to handle loaded data. UStrings don't only store the data, but try to decode them as well.

**Comment by only-a-ptr** [comment]
@Hiradur I reproduced the other issue.

I suggest incorporating the "utf8cpp" library (tiny, header-only) http://sourceforge.net/p/utfcpp/code/HEAD/tree/v2_0/source/, licensed with "boost license"  (OSI approved) https://tldrlegal.com/license/boost-software-license-1.0-explained. With this library, I can sanitize input from truckfiles, which are (by nature) saved in a variety of ANSI/OEM encodings.

**Comment by mikadou** [comment]
@only-a-ptr Maybe I'm overlooking something obvious, but I don't think input from truckfiles can be easily sanitized with that library. The main application of this library seems to be to facilitate iteration over utf8 codepoints (which may have varying byte-length). This is probaly only useful if you plan to do actual text editing, or need to count the number of visible characters instead of bytes for some other reason. Besides utf8cpp supports conversion between the different unicode types (utf8, utf16, utf32). There is no support for arbitrary encodings such as codepage latin1. To my knowledge it is sadly impossible to identify with 100% certainty the encoding used in an arbitrary textfile.

Regarding the use of MyGUI::UString, it internally uses utf16 encoding. Is there a good reason not to straightforwardly use std::string from the standard library (assuming utf8 encoding) consistently across all RoR sources (excluding parts which are considered with actual userinteface/MyGUI)?

Some good resources:
https://www.youtube.com/watch?v=n0GK-9f4dl8
http://utf8everywhere.org/

**Comment by only-a-ptr** [comment]
@mikadou :+1: for http://utf8everywhere.org/. I'll watch the video later, looks interesting, thanks.
To my best knowledge there really isn't a way to detect charset used by plaintext files with ANSI (1 byte per character) / OEM (single/multi-byte, non-unicode) encodings.

Regarding UString: #364 crashes in the moment the "Spawner report" MyGUI window is initialized. The report contains text "error in line <author>" which contains the invalid char. The text is passed as std::string, but MyGUI uses UStrings internally, there isn't a way around it.

Regarding utf8cpp: UTF8 has a scheme (https://en.wikipedia.org/wiki/UTF-8#Description) which define legal/illegal input. If the input passes this check, it's an utf8 character. The worst thing that can happen is that multiple ANSI characters, by coincidence, form a legal UTF8 sequence - well, then the user will see stray character(s), but no technical issues will occur.

**Comment by disloyalpick** [comment]
I think I may have found a work-around to this issue. Simply take all files out of packs folder, then clear cache, and put them back 20 files at a time, regenning cache after each time you place the files.
