### ISSUE TITLE
Multiplayer nicknames improvements 

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#479]
- Nicknames should not be reflected on cars or at all. (Performance impact?)
- Add the ability to hide own nickname.

![ror_2015_12_12_12_40_53_525](https://cloud.githubusercontent.com/assets/1196375/11761908/ee514c54-a0d3-11e5-8357-8f17a6234667.jpg)

**Comment by TechGiga** [comment]
I agree there shouldn't be a reflection, but if there's no nametag, nobody will know who crashed into them or so on.

**Comment by Hotrod55** [comment]
"Add the ability to hide <b>own</b> nickname."

Meaning other people will still see your nickname, but there would be a option to hide your nickname ;)

**Comment by TechGiga** [comment]
Oh, ok lol.

**Comment by Hotrod55** [comment]
I've changed the font + color of the player labels to be basically identical to 0.36.x's labels, I think it looks a lot better than the current one IMO.

The chat log from Gitter with @only-a-ptr :

**Michael10055 13:42**
>Changed the multiplayer player font color to White, looks a lot better IMO.
![1](http://i.imgur.com/AEpc2Uj.jpg)

**Petr Ohlídal 14:23**
>The multiplayer labels would look better, both on screen and in sourcecode, if they were handled as >on-screen elements rather than floating text. This way, you either use ridiculously detailed font >texture, or it looks bad almost all the time. In code, it looks bad all the time 
>On your screenshot it sure looks better, but what about bright sunny scenarios? We need to figure >some subtitle-style white text with thick black outline

**Michael10055 16:24**
>What about this? It's basically identical to 0.36.x's labels:
![2](http://i.imgur.com/NCMU4tb.jpg)

![3](http://i.imgur.com/LKifsrn.png)

>(0.36.x)

**Petr Ohlídal 18:01**
>Very nice text. How did you do that?
>However, as I said, there's the "floating text" problem - it gets too big for close objects and too tiny >for distant objects (or is there a lower/upper limit? IDK, really).

**Michael10055 18:07**
```
-- Beam.cpp line 5548-5553 ---

            netMT->setFontName("highcontrast_black");
            netMT->setTextAlignment(MovableText::H_CENTER, MovableText::V_ABOVE);
            //netMT->setAdditionalHeight(2);
            netMT->showOnTop(false);
            netMT->setCharacterHeight(2);
            netMT->setColor(ColourValue::White);
```
```
-- Character.cpp line 98-103 --

        mMoveableText->setFontName("highcontrast_black");
        mMoveableText->setTextAlignment(MovableText::H_CENTER, MovableText::V_ABOVE);
        mMoveableText->setAdditionalHeight(2);
        mMoveableText->showOnTop(false);
        mMoveableText->setCharacterHeight(8);
        mMoveableText->setColor(ColourValue::White);
```
>And yeah, the text gets bigger as the FOV decreases/camera moves away/vise versa with no limit

**Petr Ohlídal 18:13**
>Interesting, setColor(white) -> black with white outline. Guess the font is defined that way.

**Petr Ohlídal 18:21**
>The MovableText class is all wrong - full of pointlessly manual mesh/texture creation logic (probably >made for older OGRE versions) and designed to do labels as truly floating text.
>We should use either MyGUI's label widgets or custom textured polygons, but in screen space.

**Comment by only-a-ptr** [comment]
> Nicknames should not be reflected on cars or at all. (Performance impact?)

:laughing: Never noticed this, but it makes perfect sense. Performance impact should be minimal, tho, it's just a visual garbage.

Extended list of desired features:
* Upper and lower limit on text size.
* Defined min/max distance.
* No interference with game gfx (no reflections, no shader glitches...)
* Ability to toggle or disable own label.

I'd like to replace the current labels with some UI elements, such as `MyGUI::Label`-s, but there are things to consider:
* Visibility: The current labels float along players, and if the player is behind an object, so is the label. Is this desirable? A GUI label would be visible "through" all object, except if I write extra code to hide it when player is hidden. Maybe it should be toggleable.
* Mirrors: IDK if labels are currently visible in mirrors. Theoretically they should because labels are part of the scene, but maybe there's some piece missing. Anyway, displaying GUI labels in mirrors would be some extra code (minor) and some extra performance. I also don't think this is desirable - mirrors usually show small image, labels wouldn't be readable. Implementing on-screen labels for objects in mirror is possible, though, via some more code.

**Comment by Hotrod55** [comment]
The labels are visible with both the classic mirror system and videocameras: (The first picture uses videocameras, second uses the classic mirror system)
![screenshot_2016-07-20_14-58-13_1](https://cloud.githubusercontent.com/assets/11002490/16999195/cd31298a-4e8a-11e6-8426-175ad7129446.png)
![screenshot_2016-07-20_14-59-02_1](https://cloud.githubusercontent.com/assets/11002490/16999197/cfee996e-4e8a-11e6-90df-76b3c399479b.png)
But as you said, they are unreadable (and mirrored).
