### ISSUE TITLE
free_truck variable acting weird 

### ISSUE THREAD

**Issue by Max98** [RigsOfRods/rigs-of-rods#64]
Yup, I've been looking at how to delete sounds and I've came up with this. 
free_truck is simply acting weird. I've spawned a Vehicle ingame, free_truck = 1
Back to menu, the vehicle is destroyed, thus when loading an other map and an other truck it should be free_truck = 1 but no. It's free_truck = 2.
I tried to do free_truck--; on the code where the truck is deleted, then RoR goes weird (On second respawn, the vehicle is glitched).

P.S: Shouldn't free_truck mean the number of free slots?

I don't have a lot of time nor enough knowledge of RoR's spawning system for the moment to remake this but if anyone knows, would be great to fix it.

**Comment by only-a-ptr** [comment]
The truck loading/spawning logic is all wrong and I'm planning to completely rewrite it after 0.4.5 is out.

As this line of code clearly illustrates, RoR was never designed to reuse truck slots: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gameplay/RoRFrameListener.cpp#L1809. Even "reloading" a truck was actually implemented as disabling (not unloading) the old instance and creating a new one.

My plans for new system:
* Centered around RigDef::File structure (generated by RigParser)
* Will allow unlimited respawns from memory without loading the truck from disc.
* Will allow free switching between editor/simulation, always working on the same truck data.

**Comment by ulteq** [comment]
The issue with `free_truck` and consequently `trucknum` is, that we currently use the `trucknum` to generate "unique" names for our `Ogre::Material`. We can not reuse truck slots until this is fixed.

**Comment by only-a-ptr** [comment]
I'm closing this because The glitches related to mesh/material names were resolved by https://github.com/RigsOfRods/rigs-of-rods/pull/1271 and the rest is a known quirk which is about to be eliminated in near future.

the `free_truck` variable basically means "index of first unused truck slot". The original design is to never reuse slots, just fill them with NULL pointer and skip them in subsequent processing. I'm in the process of eliminating it's use-cases one by one. One remaining area I know of are sounds.
