### ISSUE TITLE
Videocamera's and MaterialFlares bugged

### ISSUE THREAD

**Issue by DevRain2500** [RigsOfRods/rigs-of-rods#656]
If you spawn a vehicle (in multiplayer) that uses materialflares or videocameras, and then someone else spawns the same vehicle after you, only the first person to spawn that vehicle has materialflares or videocameras.

Testing Vehicle: Graysonk's HDX ( http://www.rigsofrods.com/threads/120875-WIP-Beta-Released-Thomas-Saf-T-Liner-HDX )
Terrain: I used NeoQueretaro ( http://www.rigsofrods.com/threads/92748-NeoQueretaro-(urban-map-requires-0-39)?p=1176207&viewfull=1#post1176207 )

Steps:
1. Go to any multiplayer server.
2. Spawn the HDX.
3. Have someone else spawn the same vehicle.
4. Go to interior view, and you will see that no materialflares or videocameras are working for the 2nd person.

I also don't think it has to be the same vehicle. I think it may be something to do with sharing the same material files.

**Comment by graysonk95** [comment]
This has been the case for as long as meshed vehicles have existed and even occurs within a singleplayer session. Only one unique instance of a material can exist at a time.

I have often wondered if there was a way for RoR to automatically attach a unique prefix/suffix to materials and meshes to prevent this conflict, but I don't fully know how this stuff works.

Just having unique material names fixes the issue, which is how I can have multiple skinned versions of the same bus, but I have no control over material naming as more than one of the same vehicle are spawned.

**Comment by Dogy144** [comment]
I was not aware that it happened in single player as well. I'll change the title then.

**Comment by DirtGamer301** [comment]
I can second this, and will post those two issues as I think they're related:
The skinzips usually still use the same material for videocameras, and when changing a map materials aren't "cleaned".
https://github.com/RigsOfRods/rigs-of-rods/issues/402
https://github.com/RigsOfRods/rigs-of-rods/issues/506

**Comment by Dogy144** [comment]
I would also like to point out that skinzips seem to break the videocameras and material flares as well.

Vehicle Tested: http://www.rigsofrods.com/threads/120875-WIP-Beta-Released-Thomas-Saf-T-Liner-HDX (School version)

You will need to replace the .truck file with this one since the original doesn't have a GUID (Hope you don't mind @graysonk95 ): https://www.dropbox.com/s/w0ixuwhqkphzodd/Thomas_HDX-School.truck?dl=0 

SkinZip used: https://www.dropbox.com/s/rbnjg545uvruye3/DGY_Citrus_District_Schools_HDX.skinzip?dl=0
