### ISSUE TITLE
Game crash when going in setting ingame

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#664]
Hello excellent developers!

I discovered that the famous "UTF-8 continuation byte error" happened to me when I'm using my second screen in 1080p by HDMI and my G27.

[mygui.txt](https://github.com/RigsOfRods/rigs-of-rods/files/110601/mygui.txt)

For me, the thing could come for the fact it cannot support a 1080p thing :|

**Comment by WillyB1337** [comment]
Here's additional files for reference : 
[RoRConfig.txt](https://github.com/RigsOfRods/rigs-of-rods/files/110602/RoRConfig.txt)
[RoR.txt](https://github.com/RigsOfRods/rigs-of-rods/files/110603/RoR.txt)

**Comment by DirtGamer301** [comment]
I can second this bug: https://github.com/RigsOfRods/rigs-of-rods/issues/237
I don't use a 2nd monitor, and not 1080p, too, so I think that shouldn't be a thing.

I just saw I closed my issue ticker, I'll reopen it because it seems like I keep getting "Bad UTF-8 continuation byte error", so it's not actually solved, I can't remember what might have happaned some time ago, and can't remember it being fixed either ??

**Comment by only-a-ptr** [comment]
@WillyB1337 Yes the error is getting famous. The reason is known: https://github.com/RigsOfRods/rigs-of-rods/issues/237#issuecomment-177342715
