### ISSUE TITLE
Add last git commit in 'About'

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#739]
![ror_2016_02_06_18_52_45_291](https://cloud.githubusercontent.com/assets/1196375/12868236/a8be1770-cd02-11e5-8f84-c380e7a1c89f.jpg)

**Comment by Hiradur** [comment]
Minetest uses a nice versioning theme, it also checks if there were uncommited changes done to the code and adds a 'dirty' suffix if that's the case.

**Comment by mikadou** [comment]
This might be done with `git-describe`. Currently with `0.4.6.0-dev` we are using the version number which is going to be released next and append the `dev`-suffix to indicate work in progress. With `git-describe` it is easier to use the last tagged release and append the checksum of the latest commit. In addition the `dirty`-suffix can be additionally appended if the code has been modified locally.

**Comment by mikadou** [comment]
@Hiradur Are you talking about https://github.com/minetest/minetest/blob/master/CMakeLists.txt ?
They seem to specify the version inside their build system. They also provide an VERSION_EXTRA variable to append to the version string, but I don't see how the dirty suffix is automatically appended in case of modifications.

Another thing to consider is which files include the RoRVersion.h file. Because if this file changes with each commit every source file including it will be recompiled. Perhaps a global variable would be better in this case.

**Comment by Hiradur** [comment]
> Are you talking about https://github.com/minetest/minetest/blob/master/CMakeLists.txt ?

Yes, here is where the magic happens: https://github.com/minetest/minetest/blob/ffe291cb78fc7135034fe6456b2d7dfc3761dc52/cmake/Modules/GenerateVersion.cmake


> Another thing to consider is which files include the RoRVersion.h file

I think the git hash should be determined at build time and not be inside any file.

**Comment by mikadou** [comment]
I understand, it is indeed a clever versioning theme.  We should adapt this method :smirk_cat: 
I have it already half-way implemented, so I hope you doon't mind that I assigned the issue to me?

**Comment by Hiradur** [comment]
> I hope you doon't mind that I assigned the issue to me?

Not at all, I'm too busy atm anyway
