### ISSUE TITLE
Add a new optional Commands2 parameter 'playsSound'

### ISSUE THREAD

**Issue by ulteq** [RigsOfRods/rigs-of-rods#791]
As suggested by @fidoj, we should add a new optional [Commands2](http://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#commands2) parameter `playsSound` that overrides the default sound emission behavior.

**Comment by graysonk95** [comment]
In case my comment on #787 got overlooked:

"Likewise, could we also get a mute flag?

I would like to add a (working) high idle switch, but in order to do so, the high idle command beam must rev up the engine but not play the pump sound.
(A high idle switch is simulated through the use of a painfully slow command beam).

Voulk's high idle on his Thomas pack utilizes a command to rev up the engine, but he uses no pump sound at all, so his commands are effectively muted.
I use a pump sound on my HDX, so I have no way to do this without the high idle command hissing."

**Comment by ulteq** [comment]
> Likewise, could we also get a mute flag?

`playsSound 0` would basically be a mute flag.
