### ISSUE TITLE
Provide the RoR game for Linux using AppImage 

### ISSUE THREAD

**Issue by kskarthik** [RigsOfRods/rigs-of-rods#800]
Appimage helps packing apps which can run on all major Linux distributions based on concept of **one app = one file**

If RoR can be packed along with all its dependencies inside an appimage, users can simply download give permission & run the file. Mods can be added as usual from the RoR folder in the user's home directory. 

Popular apps like scribus, krita are also adopting this method to distribute their apps. It's easy to make appimage. No need extra knowledge. 

Projects repo: https://github.com/probonopd/AppImagekit

The developer @probonopd is happy to help you packing your app :)

**Comment by Hiradur** [comment]
Since you proposed that to me privately a few months ago I intended to do it but I haven't really found the time (and motivation, I have to admit).

Recently I wondered though if a static build wouldn't be more elegant. I like how OpenArena distribute their game: a single download which contains static binaries for Windows, Linux 32bit and Linux 64bit.
The advantages are:
- may save traffic for the host: one download is enough to run the game on Windows and Linux PCs in a household
- it's easy to share with friends regardless of which OS they use
- Linux only: easy installation of the latest version which may not make it into the software repository for the used distribution (e.g. Debian stable)

This could probably also be done with an AppImage and may be easier for the developer but I suspect the directory of the game would look more cluttered.

**Comment by kskarthik** [comment]
Okay. That's a good implementation for this game. One binary targeting multiple OS's :) AppImage can't do that.

**Comment by kskarthik** [comment]
@hitadur This is a similar software like appimage for Windows too. 

 http://portableapps.com/development you might know this. 

These formats save the user's disk space since they are compressed all the time.

**Comment by Hiradur** [comment]
> One binary targeting multiple OS's :) AppImage can't do that. 

Technically it's 3 separate binaries, one for each OS. A single binary for multiple OS's is impossible AFAIK.

> http://portableapps.com/development you might know this. 

I know about portableapps but distribution on Windows is not really a problem, at least nobody complained about it yet.

> These formats save the user's disk space since they are compressed all the time.

I don't believe disk space is an issue for computers which are able to run RoR. Regardless, it's the content which eats up space. E.g. the high quality pack already takes up 1GB of space compared to 100-200mb for the RoR install itself even though the mods are already compressed.

**Comment by probonopd** [comment]
Actually, since an AppImage is an ISO file, it is possible to put binaries for Linux, OS X, and Windows inside.

To mount:
http://www.howtogeek.com/230468/how-to-mount-isos-and-other-disc-images-on-windows-mac-and-linux/

**Comment by Hiradur** [comment]
@probonopd 
Good to know. Once version 0.4.6 is released I'll give this a try.

**Comment by probonopd** [comment]
Why was this closed?
