### ISSUE TITLE
Default installation of Rigs of Rods lacks content

### ISSUE THREAD

**Issue by picy680** [RigsOfRods/rigs-of-rods#835]
yeah RoR is really crappy now the are 3 truck and 2 maps i watched the videos of it then got it and its not what it was or what the videos look like

**Comment by AntoniD330** [comment]
@picy680 You've just downloaded the basic game with basic content.
You can download content from our repository backup [here](https://repofiles.avrintech.net/).
Others links:
[New Showroom](http://rigsofrods.org//forum-6.html) and the old one [here] (http://www.rigsofrods.org/old-forum/forums/103-Section-Show/page-0001.html).

**Comment by Hiradur** [comment]
Should RoR ship with a few more mods by default? The problem here would be increased download size/traffic and more importantly the license of the mods since it would have to be compatible with the GPLv3. I don't know of any mods which are.

**Comment by Bob-Z** [comment]
Regarding download size/traffic, would it be possible to include some kind of bittorrent client inside RoR which will load data when needed from both main server and other connected RoR clients ?

**Comment by Hiradur** [comment]
> Regarding download size/traffic, would it be possible to include some kind of bittorrent client inside RoR which will load data when needed from both main server and other connected RoR clients ?

two issues which come to my mind right now:
- copyright violation: what if the mods are not freely licensed but automatically downloaded/uploaded?
- redundancy: with all the modded vehicles floating around there is potential for a lot of redundancy which would need to be taken into account for the design.

btw: By traffic I was talking about the traffic of cloning the repository. The better way IMO is to include an option to download the content packs separately. This option was already included in the Windows installer at one time.
My linux scripts also offer an option to download the content packs.

**Comment by Bob-Z** [comment]
Thanks Hiradur for your answer. Let me be more specific on what I have in mind:

We could have a single torrent file hosted on RoR site. This file would be downloaded at RoR start-up. RoR would parse this file to add its content in the relevant user menus (map/vehicule). When users select one of its entry a classical BitTorrent download would happens. Of course, already downloaded files would be shared through BitTorrent network.

Since the default torrent file would be hosted on RoR site, only selected mods could be added in it. So we can have license compliant, non redundant and bug free mods.

This is more flexible than a monolithic content file. Support for those mods would be simplified since they could easily be updated in case of bug/enhancements, and bug reports for them would be more easily reproducible.

Anyway, this just an idea, and I don't have enough time/motivation to propose you a proof of concept.

**Comment by CuriousMike56** [comment]
The installer now includes the option to download content packs. I think this can be closed now.
